name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Release only if the 'version' field in Chart.yaml was updated
    paths:
      - charts/**/Chart.yaml

jobs:
  release:
    if: github.repository == 'splunk/synthetics-helm-charts'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Validate Chart.yaml Update
        id: check_update_chart
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/splunk/synthetics-helm-charts/releases/latest | grep tag_name | cut -d - -f 4 | cut -d \" -f 1)
          CURRENT_VERSION=$(cat charts/splunk-synthetics-runner/Chart.yaml | grep -E "^version:" | cut -d " " -f 2)
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "New release needed, creating..."
            echo "VALID_UPDATE=1" >> $GITHUB_OUTPUT
          else
            echo "No new release needed"
            echo "VALID_UPDATE=0" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        if: ${{ steps.check_update_chart.outputs.VALID_UPDATE == 1 }}

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        if: ${{ steps.check_update_chart.outputs.VALID_UPDATE == 1 }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: ${{ steps.check_update_chart.outputs.VALID_UPDATE == 1 }}
